### ISSUE TITLE
ReferenceError: __non_webpack_require__ is not defined at patchSharing

### ISSUE THREAD

**Issue by AlienDev66** [agoldis/webpack-require-from#61]

**Comment by AlienDev66** [comment]
ReferenceError: __non_webpack_require__ is not defined
    at patchSharing (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/@module-federation/nextjs-mf/patchSharing.js:5:34)
    at MyDocument.render (webpack-internal:///./pages/_document.tsx:28:99)
    at processChild (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3450:18)
    at resolve (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at renderDocument (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/next/dist/next-server/server/render.js:3:725)
    at renderToHTML (/home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/next/dist/next-server/server/render.js:56:103)
    at async /home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/next/dist/next-server/server/next-server.js:109:97
    at async /home/domingos/www/module-federation-examples/iss-micro-frontend/node_modules/next/dist/next-server/server/next-server.js:102:142

**Comment by agoldis** [comment]
Hey @AlienDev66 
Can you please provide more context?
